---
###############################################################################
#                           Authelia Configuration                            #
#                           Notifier Configuration                            #
###############################################################################

  ## File System (Notification Provider)
  # filesystem:
  #   filename: /config/notification.txt

  ## SMTP (Notification Provider)
  ## Use a SMTP server for sending notifications. Authelia uses the PLAIN or LOGIN methods to authenticate.
  ## [Security] By default Authelia will:
  ##   - force all SMTP connections over TLS including unauthenticated connections
  ##      - use the disable_require_tls boolean value to disable this requirement
  ##        (only works for unauthenticated connections)
  ##   - validate the SMTP server x509 certificate during the TLS handshake against the hosts trusted certificates
  ##     (configure in tls section)


notifier:
  disable_startup_check: false
  smtp:
    host: smtp.sendgrid.net
    port: 465
    timeout: 5s
    username: apikey
  #   password: IN FILE
    sender: "Authelia <noreply@example.com>"
  #   identifier: localhost
    subject: "[Authelia] {title}"
  #   startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: smtp.sendgrid.net
      skip_verify: false
      minimum_version: TLS1.2
...
